spring.application.name=arcapi

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/cloud_storage
spring.datasource.username=root
spring.datasource.password=DB11GTRS3

# Hibernate Configuration

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl.auto=update
spring.jpa..properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database=mysql

#spring.main.allow-circular-references=true

